### ISSUE TITLE
The warning about caching won't go away

### ISSUE THREAD

**Issue by artm** [titusfortner/webdrivers#118]
#### Summary

I keep getting the warning:

```
WARN Webdrivers Driver caching is turned off in this version, but will be enabled 
by default in 4.x. Set the value with `Webdrivers#cache_time=` in seconds
```

I have tried to set `Webdrivers.cache_time= ...` at various points in the test suite initialization without success.

#### Debug Info
Please provide the following information for bug reports:

* Operating system / CI Environment: Linux
* Browser and version: not relevant

#### Expected Behavior
The warning to go away

#### Actual Behavior
It doesn't

**Comment by titusfortner** [comment]
You're right, I didn't put the correct conditional here. I'm hoping we get 4.0 beta released soon, and a production release soon after. I'm leaning toward that than another point release fixing this.

**Comment by titusfortner** [comment]
Fixed with #121 and released in 3.9.3

**Comment by PatrickMcSweeny** [comment]
I updated to version 3.9.3 and I am still getting the warning.

**Comment by kevinhq** [comment]
> I updated to version 3.9.3 and I am still getting the warning.

Yes. still got this warning. Is there any chance to re-open this issue?

**Comment by richdownie** [comment]
I am still seeing the warning in 3.9.3

**Comment by titusfortner** [comment]
This is what I get for not making sure there was a test. Let me look.

**Comment by richdownie** [comment]
Thanks Titus

**Comment by titusfortner** [comment]
3.9.4 released (with spec) should be good now.

**Comment by PatrickMcSweeny** [comment]
Maybe I'm missing something, but I updated to 3.9.4 and I'm still getting the warning even after running my tests multiple times.

**Comment by PatrickMcSweeny** [comment]
Nevermind, I set a value for cache_time and the warning doesn't appear.

**Comment by jrochkind** [comment]
The README still says:

`Webdrivers.cache_time = 86_400 # Default: 86,400 Seconds (24 hours)`

It suggests there is a default, which suggests if you want the default you don't need to set it manually. 

But the deprecation warning suggests Webdrivers wants you to set it manually, and in the future you will have to set it manually and there will be no default. 

Can you update the README to explain what it is suggested one does? I think one has to put that configure line somewhere in one's app (perhaps test_helper.rb or spec_helper.rb) and perhaps it is suggested you set it to 86_400?

**Comment by kapoorlakshya** [comment]
Hey @jrochkind, which version of the gem are you using? The cache time warning was removed in v4.0 and the value was properly defaulted to 24 hours in v4.0.1. 

> Can you update the README to explain what it is suggested one does?

`test_helper` or `spec_helper` are preferred, but it can be anywhere before your test launches the browser. This is only required if you want the cache time to be > 24 hours.

**Comment by jrochkind** [comment]
Aha, I am using 3.94. 

Sounds like it's time to update to 4.0, ok! I put `~> 3.0` in my Gemfile, so requires an edit to get 4; and of course the README in master is for 4, it all makes sense now. I didn't totally realize 4 was out.
